import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.mashape.unirest.http.*;
import com.mashape.unirest.http.exceptions.UnirestException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Weather {
    public static void main(String[] args) throws Exception {
        Gson gson = new GsonBuilder().setPrettyPrinting().create();

        final String REQUEST_URL = "http://reqres.in/api/users?page=2";
        HttpResponse<JsonNode> response = Unirest.get(REQUEST_URL)
                .asJson();
        String jsonRaw = response.getBody().toString();
        Map<String,Object> result = new HashMap<String,Object>();
        result = (Map<String,Object>) gson.fromJson(jsonRaw , Map.class);
        String asd = result.get("data").toString();
        System.out.println(asd);
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
